### ISSUE TITLE
Почему возникла ошибка 

### ISSUE THREAD

**Issue by Sirgalas** [Friday14/cloud-mail-ru#1]
Вот [здесь](https://github.com/Friday14/mailru-cloud-php/blob/master/src/Cloud.php)     в константе DOWNLOAD_URL строка 26 определен адрес `https://cloclo27.datacloudmail.ru/`  сейчас все картинки у меня сохраняются по этому адресу (дальше вопросов нет)`https://cloclo17.datacloudmail.ru/` с чем связана ошибка? Вопрос сушественый, так как адресса сохраняются абослютно, а не диномически . И если это mail.ru так поступает, то надо каким то образом решать вопрос о динамическом сохранении адрессов с возможностью сохранения адресса в локальных параметрах.

**Comment by em7v** [comment]
Посмотрю в течении недели (Преимущественно сб-вск). И отпишу.
